package projetTransport.parser.javacc.bus;/* Generated By:JavaCC: Do not edit this line. BusJsonConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface BusJsonConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int OPENING_BRACE = 2;
  /** RegularExpression Id. */
  int CLOSING_BRACE = 3;
  /** RegularExpression Id. */
  int OPENING_BRACKET = 4;
  /** RegularExpression Id. */
  int CLOSING_BRACKET = 5;
  /** RegularExpression Id. */
  int COMMA = 6;
  /** RegularExpression Id. */
  int LIGNE = 7;
  /** RegularExpression Id. */
  int HORAIRES = 8;
  /** RegularExpression Id. */
  int DIRECTION = 9;
  /** RegularExpression Id. */
  int STATIONS = 10;
  /** RegularExpression Id. */
  int STATION = 11;
  /** RegularExpression Id. */
  int PASSAGES = 12;
  /** RegularExpression Id. */
  int WORD = 13;
  /** RegularExpression Id. */
  int TIME = 14;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "<token of kind 1>",
    "\"{\"",
    "\"}\"",
    "\"[\"",
    "\"]\"",
    "\",\"",
    "<LIGNE>",
    "<HORAIRES>",
    "<DIRECTION>",
    "<STATIONS>",
    "<STATION>",
    "<PASSAGES>",
    "<WORD>",
    "<TIME>",
  };

}
