package projetTransport.parser.javacc.car;/* Generated By:JavaCC: Do not edit this line. CarTxtConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface CarTxtConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int WORD = 3;
  /** RegularExpression Id. */
  int TIME = 4;
  /** RegularExpression Id. */
  int NEW_LINE = 5;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "<token of kind 1>",
    "<token of kind 2>",
    "<WORD>",
    "<TIME>",
    "\"\\n\"",
    "\"//\"",
  };

}
