package projetTransport.parser.javacc.train;/* Generated By:JavaCC: Do not edit this line. TrainXmlConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface TrainXmlConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int WORD = 3;
  /** RegularExpression Id. */
  int INTEGER = 4;
  /** RegularExpression Id. */
  int HORAIRES = 5;
  /** RegularExpression Id. */
  int LIGNE = 6;
  /** RegularExpression Id. */
  int JUNCTION = 7;
  /** RegularExpression Id. */
  int START_STATION = 8;
  /** RegularExpression Id. */
  int ARRIVAL_STATION = 9;
  /** RegularExpression Id. */
  int START_HOUR = 10;
  /** RegularExpression Id. */
  int ARRIVAL_HOUR = 11;
  /** RegularExpression Id. */
  int HORAIRES_CLOSE = 12;
  /** RegularExpression Id. */
  int LIGNE_CLOSE = 13;
  /** RegularExpression Id. */
  int JUNCTION_ClOSE = 14;
  /** RegularExpression Id. */
  int START_STATION_CLOSE = 15;
  /** RegularExpression Id. */
  int ARRIVAL_STATION_CLOSE = 16;
  /** RegularExpression Id. */
  int START_HOUR_CLOSE = 17;
  /** RegularExpression Id. */
  int ARRIVAL_HOUR_CLOSE = 18;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\"<?xml version=\\\'1.0\\\' encoding=\\\'UTF-8\\\' ?>\\n\"",
    "<token of kind 2>",
    "<WORD>",
    "<INTEGER>",
    "\"<horaires>\"",
    "\"<line>\"",
    "\"<junction>\"",
    "\"<start-station>\"",
    "\"<arrival-station>\"",
    "\"<start-hour>\"",
    "\"<arrival-hour>\"",
    "\"</horaires>\"",
    "\"</line>\"",
    "\"</junction>\"",
    "\"</start-station>\"",
    "\"</arrival-station>\"",
    "\"</start-hour>\"",
    "\"</arrival-hour>\"",
  };

}
