package projetTransport.parser.javacc.tram;/* Generated By:JavaCC: Do not edit this line. TramXmlConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface TramXmlConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int WORD = 3;
  /** RegularExpression Id. */
  int INTEGER = 4;
  /** RegularExpression Id. */
  int RESAU = 5;
  /** RegularExpression Id. */
  int LIGNES = 6;
  /** RegularExpression Id. */
  int LIGNE = 7;
  /** RegularExpression Id. */
  int STATIONS = 8;
  /** RegularExpression Id. */
  int HEURES_PASSAGE = 9;
  /** RegularExpression Id. */
  int RESAU_CLOSE = 10;
  /** RegularExpression Id. */
  int LIGNES_CLOSE = 11;
  /** RegularExpression Id. */
  int LIGNE_CLOSE = 12;
  /** RegularExpression Id. */
  int STATIONS_CLOSE = 13;
  /** RegularExpression Id. */
  int HEURES_PASSAGE_CLOSE = 14;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\"<?xml version=\\\'1.0\\\' encoding=\\\'UTF-8\\\' ?>\\n\"",
    "<token of kind 2>",
    "<WORD>",
    "<INTEGER>",
    "\"<reseau>\"",
    "\"<lignes>\"",
    "\"<ligne>\"",
    "\"<stations>\"",
    "\"<heures-passage>\"",
    "\"</reseau>\"",
    "\"</lignes>\"",
    "\"</ligne>\"",
    "\"</stations>\"",
    "\"</heures-passage>\"",
  };

}
